In [13]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [14]:
def randUniform(a, b):
  return np.random.rand() * (b - a) + a;

def make_gaussion(cx,cy,label,n):
    data = np.random.rand(n,3)
    for i in range(n):
        x = randUniform(cx,randUniform(cx))
        y = normalRandom(cy, randUniform(cy));
        data[i][0] = x
        data[i][1] = y
        data[i][2] = label
    return data

In [12]:
make_gaussion(10)

(array([[0.03824707, 0.74857146],
        [0.30951189, 0.92319373],
        [0.47844547, 0.68532961],
        [0.84154575, 0.91877055],
        [0.32980656, 0.61998702],
        [0.50064016, 0.23403675],
        [0.56119586, 0.65764829],
        [0.67562205, 0.95235228],
        [0.47623036, 0.35607398],
        [0.72257967, 0.32949381]]),
 array([1, 1, 1, 0, 1, 1, 1, 1, 1, 0]))

In [10]:
np.random.randint(0, 2,size=10)

array([0, 0, 1, 1, 0, 1, 0, 0, 1, 0])