In [4]:
import tensorflow as tf
from tensorflow.keras.layers import TextVectorization

In [22]:
# text tokenization
text_dataset = tf.data.Dataset.from_tensor_slices(["i", "love", "tensorflow",'rocks'])
text_vec = TextVectorization()
text_vec.adapt(text_dataset)
# print the vocabulary
vocab = text_vec.get_vocabulary()
for i,v in enumerate(vocab):
    print(f'vocabulary at index {i} is {v}')
len_of_vocabulary = len(vocab)
print(f'len of vocabulary {len_of_vocabulary}')

vocabulary at index 0 is 
vocabulary at index 1 is [UNK]
vocabulary at index 2 is tensorflow
vocabulary at index 3 is rocks
vocabulary at index 4 is love
vocabulary at index 5 is i
len of vocabulary 6


In [21]:
# sample sentence
sample_1 = 'I Love Tensorflow'
vec_1 = text_vec([sample])
print(f'sample 1 sentence \n {sample_1}\
        vector representation \n {vec_1}')

sample 1 sentence 
 I Love Tensorflow        vector representation 
 [[5 4 2]]


In [29]:
# another sample
sample_2 = 'Tensorflow I rocks'
vec_2 = text_vec([sample_2])
print(f'sample 2 sentence \n {sample_2}\
        vector representation \n {vec_2}')

sample 2 sentence 
 Tensorflow I rocks        vector representation 
 [[2 5 3]]


In [33]:
# embedding 
from tensorflow.keras.layers import Embedding

embedding = Embedding(input_dim=len_of_vocabulary,
                     output_dim=4,
                     input_length=4)
embedding

In [34]:
embedding(vec_1)

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[-0.00546367,  0.0182437 , -0.01037307, -0.03953638],
        [-0.00939064,  0.00924812, -0.01262503, -0.04210285],
        [ 0.01576029,  0.03825409,  0.0430048 ,  0.04823674]]],
      dtype=float32)>

In [35]:
# embedding for second sample sentence
embedding(vec_2)

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[ 0.01576029,  0.03825409,  0.0430048 ,  0.04823674],
        [-0.00546367,  0.0182437 , -0.01037307, -0.03953638],
        [-0.01690295,  0.04698409,  0.00048009, -0.04678594]]],
      dtype=float32)>

In [38]:
tmp = embedding(vec_2)
tmp.shape

TensorShape([1, 3, 4])