In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
#scikit
from sklearn.preprocessing import PolynomialFeatures

In [5]:
df = pd.read_csv('Advertising.csv')
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [6]:
X = df.drop('sales', axis=1)
y = df['sales']

In [7]:
polynomial_converter = PolynomialFeatures(degree=3, include_bias=False)

In [8]:
poly_features = polynomial_converter.fit_transform(X)

In [9]:
poly_features.shape

(200, 19)

In [10]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
     poly_features, y, test_size=0.3, random_state=101)

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scaler = StandardScaler()

In [16]:
scaler.fit(X_train)

StandardScaler()

In [17]:
X_train = scaler.transform(X_train)

In [18]:
X_train.shape

(140, 19)

In [19]:
X_test = scaler.transform(X_test)

<p> Ridge Regression</p>

In [20]:
from sklearn.linear_model import Ridge

In [21]:
ridge_model = Ridge(alpha=10)

In [22]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [23]:
test_prediction = ridge_model.predict(X_test)

In [24]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [25]:
MAE = mean_absolute_error(y_test,test_prediction)

In [26]:
MAE

0.5774404204714183

In [27]:
RMSE = np.sqrt(mean_squared_error(y_test,test_prediction))

In [28]:
RMSE

0.8946386461319686

<p>Ridge Regression Cross Validation</p>

In [29]:
from sklearn.linear_model import RidgeCV

In [36]:
ridge_cv_model = RidgeCV(alphas=(0.1,1.0,10.0),scoring='neg_median_absolute_error')

In [37]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(scoring='neg_median_absolute_error')

In [38]:
ridge_cv_model.alpha_

0.1

In [34]:
#from sklearn.metrics import SCORERS

In [39]:
#SCORERS.keys()

In [40]:
test_pred = ridge_cv_model.predict(X_test)

In [41]:
MAE = mean_absolute_error(y_test,test_pred)

In [42]:
MAE

0.42737748843373746

In [43]:
RMSE = np.sqrt(mean_squared_error(y_test,test_pred))

In [44]:
RMSE

0.6180719926921404

In [45]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

<p>LASSO(Least Absolute Shrinkage & Selection Operator) Regression</p>

In [46]:
from sklearn.linear_model import LassoCV

In [59]:
lasso_cv_model = LassoCV(eps=0.1,n_alphas=100,cv=5)

In [60]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, eps=0.1)

In [61]:
test_pred = lasso_cv_model.predict(X_test)

In [62]:
MAE = mean_absolute_error(y_test,test_pred)

In [63]:
MAE

0.6541723161252854

In [64]:
RMSE = np.sqrt(mean_squared_error(y_test,test_pred))

In [65]:
RMSE

1.130800102276253

In [66]:
lasso_cv_model.alpha_

0.4943070909225828

In [67]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

<p> Elastic Net Regression</p>

In [69]:
from sklearn.linear_model import ElasticNetCV

In [72]:
elastic_model = ElasticNetCV(l1_ratio=[.1,.5,.7,.9,.95,.99,1],
                            eps=0.001,n_alphas=100,max_iter=1000000)

In [73]:
elastic_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [74]:
pred = elastic_model.predict(X_test)

In [75]:
MSE = mean_absolute_error(y_test,pred)

In [76]:
MSE

0.43350346185900673

In [77]:
RMSE = np.sqrt(mean_squared_error(y_test,pred))

In [78]:
RMSE

0.6063140748984039

In [79]:
elastic_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

In [82]:
elastic_model.l1_ratio_

1.0

In [83]:
elastic_model.alpha_

0.004943070909225827

In [84]:
lasso_cv_model.alpha_

0.4943070909225828