In [1]:
import nltk
import numpy as np
import pandas as pd

from nltk import word_tokenize

In [2]:
df = pd.read_csv('bbc_text_cls.csv')
df

text    labels
0     Ad sales boost Time Warner profit\n\nQuarterly...  business
1     Dollar gains on Greenspan speech\n\nThe dollar...  business
2     Yukos unit buyer faces loan claim\n\nThe owner...  business
3     High fuel prices hit BA's profits\n\nBritish A...  business
4     Pernod takeover talk lifts Domecq\n\nShares in...  business
...                                                 ...       ...
2220  BT program to beat dialler scams\n\nBT is intr...      tech
2221  Spam e-mails tempt net shoppers\n\nComputer us...      tech
2222  Be careful how you code\n\nA new European dire...      tech
2223  US cyber security chief resigns\n\nThe man mak...      tech
2224  Losing yourself in online gaming\n\nOnline rol...      tech

[2225 rows x 2 columns]

In [3]:
# word2idx function
def word2index(corpus):
    idx = 0
    word2idx = {}
    tokenized_docs = []
    for doc in corpus['text']:
        words = word_tokenize(doc.lower())
        doc_as_int = []
        for word in words:
            if word not in word2idx:
                word2idx[word] = idx
                idx += 1
            doc_as_int.append(word2idx[word])
        
        tokenized_docs.append(doc_as_int)
        
    return word2idx,tokenized_docs

def index2word(idx,word2idx):
    res = []
    print(idx)
    for i in idx:
        print(i)
        res.append(word2idx[i])
    return ''.join(res)

In [4]:
my_array = np.array([['Ad sales boost Time Warner '],['Losing Time in online gaming']])
df = pd.DataFrame(my_array, columns = ['text'])
df

text
0   Ad sales boost Time Warner 
1  Losing Time in online gaming

In [5]:
dictionary,tokenized_docs = word2index(df)
print('dictionary',dictionary)
print('tokenized_docs',tokenized_docs)

dictionary {'ad': 0, 'sales': 1, 'boost': 2, 'time': 3, 'warner': 4, 'losing': 5, 'in': 6, 'online': 7, 'gaming': 8}
tokenized_docs [[0, 1, 2, 3, 4], [5, 3, 6, 7, 8]]


In [6]:
dictionary.items()

dict_items([('ad', 0), ('sales', 1), ('boost', 2), ('time', 3), ('warner', 4), ('losing', 5), ('in', 6), ('online', 7), ('gaming', 8)])

In [19]:
idx2word = []
for v,k in dictionary.items():
    idx2word.append(v)
print(idx2word)

['ad', 'sales', 'boost', 'time', 'warner', 'losing', 'in', 'online', 'gaming']


In [8]:
# no of docs
N = len(df['text'])
print(N)

2


In [9]:
# no of words
V = len(dictionary)
print(V)

9


In [22]:
# tfidf matrix - term frequency matrix
tf = np.zeros((N,V))
print('before\n',tf)
# frequency counts
def count_vectorizor(tf):
   for i, doc_as_int in enumerate(tokenized_docs):
    for j in doc_as_int:
        tf[i,j] +=1
        
count_vectorizor(tf)
print('after\n',tf)

before
 [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
after
 [[1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1. 1. 1. 1.]]


In [27]:
document_frequency = np.sum(tf>0,axis=0)
idf = np.log(N/document_frequency)
print(idf)

[0.69314718 0.69314718 0.69314718 0.         0.69314718 0.69314718
 0.69314718 0.69314718 0.69314718]


In [28]:
tf_idf = tf * idf
print(tf_idf)

[[0.69314718 0.69314718 0.69314718 0.         0.69314718 0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.69314718
  0.69314718 0.69314718 0.69314718]]


In [38]:
scores = tf_idf[0]
indices = scores.argsort()
print(scores)
print(indices)
#indices = (-scores).argsort()
#print(indices)

[0.69314718 0.69314718 0.69314718 0.         0.69314718 0.
 0.         0.         0.        ]
[3 5 6 7 8 0 1 2 4]


In [39]:
for j in indices[:5]:
    print(j, idx2word[j])

3 time
5 losing
6 in
7 online
8 gaming
