In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
doc = ['ipad apple','galaxy samsung','iphone apple','smart samsung']
tf = TfidfVectorizer(analyzer='word',stop_words='english')
tfidf_matrix = tf.fit_transform(doc)

In [3]:
tfidf_matrix

<4x6 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [4]:
tfidf_matrix.todense()

matrix([[0.6191303 , 0.        , 0.78528828, 0.        , 0.        ,
         0.        ],
        [0.        , 0.78528828, 0.        , 0.        , 0.6191303 ,
         0.        ],
        [0.6191303 , 0.        , 0.        , 0.78528828, 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.6191303 ,
         0.78528828]])

In [5]:
#ipad apple galaxy samsung iphone 14 something

In [6]:
tf.get_feature_names_out()

array(['apple', 'galaxy', 'ipad', 'iphone', 'samsung', 'smart'],
      dtype=object)

In [7]:
from sklearn.metrics.pairwise import cosine_similarity,euclidean_distances

In [20]:
x = tfidf_matrix.todense()[0]
type(x.squeeze())

numpy.matrix

In [24]:
nda = cosine_similarity(tfidf_matrix)

In [23]:
cosine_similarity(tfidf_matrix,tfidf_matrix)

array([[1.        , 0.        , 0.38332232, 0.        ],
       [0.        , 1.        , 0.        , 0.38332232],
       [0.38332232, 0.        , 1.        , 0.        ],
       [0.        , 0.38332232, 0.        , 1.        ]])

In [34]:
cosine_similarity(nda[0].reshape(1, -1) ,nda[2].reshape(1, -1) )

array([[0.66842844]])

In [35]:
nda[0].reshape(1, -1)

array([[1.        , 0.        , 0.38332232, 0.        ]])

In [56]:
doc = ['good night','good bye']
tf = TfidfVectorizer(analyzer='word',stop_words='english')
tfidf_matrix = tf.fit_transform(doc)

In [57]:
tf.get_feature_names_out()

array(['bye', 'good', 'night'], dtype=object)

In [62]:
import pandas as pd

In [74]:
doc2idx = pd.Series([0,1],index=doc)
idx = doc2idx['good night']
idx

0

In [75]:
query = tfidf_matrix[idx]
query

<1x3 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [76]:
query.toarray()

array([[0.        , 0.57973867, 0.81480247]])

In [79]:
doc2idx = pd.Series([0,1],index=doc)
idx = doc2idx['good bye']
idx

1

In [80]:
query = tfidf_matrix[idx]
query

<1x3 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [81]:
query.toarray()

array([[0.81480247, 0.57973867, 0.        ]])

In [83]:
scores = cosine_similarity(query,tfidf_matrix)
scores

array([[0.33609693, 1.        ]])

In [84]:
scores.flatten()

array([0.33609693, 1.        ])