<b>NumPy Arrays</b>

In [2]:
import numpy as np

In [3]:
mylist = [1,2,3,4,5]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3, 4, 5])

In [6]:
myarr = np.array(mylist)

In [7]:
type(myarr)

numpy.ndarray

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
len(np.linspace(0,10,11))

11

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(5,6)

array([[0.31674099, 0.73705781, 0.84286894, 0.37694057, 0.92826133,
        0.33871266],
       [0.42352018, 0.28791619, 0.44599914, 0.36472279, 0.10531203,
        0.62613336],
       [0.85440263, 0.42903478, 0.96028987, 0.53670289, 0.55079756,
        0.58248938],
       [0.96867149, 0.01142209, 0.57863759, 0.30137453, 0.79097293,
        0.73814804],
       [0.80910603, 0.32409117, 0.68036193, 0.38551911, 0.78688655,
        0.52461343]])

In [25]:
np.random.randn(10)

array([-0.40280414,  2.00312804,  1.20950749, -1.38185108, -1.60836075,
        2.14936056,  1.49087404, -1.44610205,  0.43859623,  0.48292808])

In [26]:
np.random.randn(2,3)

array([[-0.53358179, -0.66462269,  1.63497017],
       [ 2.19820371, -1.66176649,  1.63273265]])

In [30]:
np.random.randint(0,101,(4,5))

array([[50,  0, 17, 79, 19],
       [ 3,  8, 69, 18, 84],
       [94,  9, 12, 75, 16],
       [84, 45, 85, 65, 94]])

In [32]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [34]:
arr = np.arange(0,25)

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
ranarr = np.random.randint(0,101,10)

In [37]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [38]:
ranarr.min()

2

In [39]:
ranarr.argmax()

5

In [40]:
ranarr.dtype

dtype('int32')

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
arr.shape

(25,)

In [43]:
arr = arr.reshape(5,5)

In [44]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
arr.shape

(5, 5)

In [46]:
arr = np.arange(0,11)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[8]

8

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [52]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [54]:
arr_2d.shape

(3, 3)

In [55]:
arr_2d[-1]

array([35, 40, 45])

In [56]:
arr_2d[0,2]

15

In [57]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
bool_arr = arr > 4

In [60]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [61]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [62]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [63]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [64]:
dice_rolls

array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6,
       3, 6, 2, 3, 5, 6, 5])

In [65]:
dice_rolls[dice_rolls > 2]

array([3, 5, 5, 5, 4, 4, 5, 3, 4, 5, 4, 6, 6, 3, 6, 3, 5, 6, 5])

In [67]:
len(dice_rolls[dice_rolls > 2])

19

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [70]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [71]:
arr/arr

C:\Users\rupak\AppData\Local\Temp\ipykernel_15972\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [72]:
np.log(arr)

C:\Users\rupak\AppData\Local\Temp\ipykernel_15972\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [73]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [74]:
arr.sum()

55

In [75]:
arr.var()

10.0

In [76]:
arr.std()

3.1622776601683795

In [77]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [78]:
np.sum(arr_2d)

225

In [80]:
np.sum(arr_2d,axis=0)

array([60, 75, 90])

In [81]:
arr_2d.sum(axis=0)

array([60, 75, 90])

In [82]:
np.sum(arr_2d,axis=1)

array([ 30,  75, 120])